from math import sin,cos,pi
import numpy as np


q1 = q2 = q3 = q4 = 0.0
q1 = 0.0
vels = np.array([q1,q2,q3,q4])
J = [
            
                    [133.4000*cos(q4)*(sin(q1)*sin(q2)*sin(q3) - cos(q2)*cos(q3)*sin(q1)) - 128*cos(q2)*sin(q1) + 133.4000*sin(q4)*(cos(q2)*sin(q1)*sin(q3) + cos(q3)*sin(q1)*sin(q2)) + 148*sin(q1)*sin(q2)*sin(q3) - 148*cos(q2)*cos(q3)*sin(q1),                                                                                                                                                                                                                                                                                                  -cos(q1)*(128*sin(q2) + 148*cos(q2)*sin(q3) + 148*cos(q3)*sin(q2) + 133.4000*cos(q4)*(cos(q2)*sin(q3) + cos(q3)*sin(q2)) + 133.4000*sin(q4)*(cos(q2)*cos(q3) - sin(q2)*sin(q3))),                                                                                                                                                                                                                                                                    -cos(q1)*(148*cos(q2)*sin(q3) + 148*cos(q3)*sin(q2) + 133.4000*cos(q4)*(cos(q2)*sin(q3) + cos(q3)*sin(q2)) + 133.4000*sin(q4)*(cos(q2)*cos(q3) - sin(q2)*sin(q3))),                                                                                                                                                                                        -cos(q1)*(133.4000*cos(q4)*(cos(q2)*sin(q3) + cos(q3)*sin(q2)) + 133.4000*sin(q4)*(cos(q2)*cos(q3) - sin(q2)*sin(q3)))],
                    [128*cos(q1)*cos(q2) + 133.4000*cos(q4)*(cos(q1)*cos(q2)*cos(q3) - cos(q1)*sin(q2)*sin(q3)) - 133.4000*sin(q4)*(cos(q1)*cos(q2)*sin(q3) + cos(q1)*cos(q3)*sin(q2)) + 148*cos(q1)*cos(q2)*cos(q3) - 148*cos(q1)*sin(q2)*sin(q3),                                                                                                                                                                                                                                                                                                  -sin(q1)*(128*sin(q2) + 148*cos(q2)*sin(q3) + 148*cos(q3)*sin(q2) + 133.4000*cos(q4)*(cos(q2)*sin(q3) + cos(q3)*sin(q2)) + 133.4000*sin(q4)*(cos(q2)*cos(q3) - sin(q2)*sin(q3))),                                                                                                                                                                                                                                                                    -sin(q1)*(148*cos(q2)*sin(q3) + 148*cos(q3)*sin(q2) + 133.4000*cos(q4)*(cos(q2)*sin(q3) + cos(q3)*sin(q2)) + 133.4000*sin(q4)*(cos(q2)*cos(q3) - sin(q2)*sin(q3))),                                                                                                                                                                                        -sin(q1)*(133.4000*cos(q4)*(cos(q2)*sin(q3) + cos(q3)*sin(q2)) + 133.4000*sin(q4)*(cos(q2)*cos(q3) - sin(q2)*sin(q3)))],
                    [                                                                                                                                                                                                                            0, sin(q1)*(133.4000*cos(q4)*(sin(q1)*sin(q2)*sin(q3) - cos(q2)*cos(q3)*sin(q1)) - 128*cos(q2)*sin(q1) + 133.4000*sin(q4)*(cos(q2)*sin(q1)*sin(q3) + cos(q3)*sin(q1)*sin(q2)) + 148*sin(q1)*sin(q2)*sin(q3) - 148*cos(q2)*cos(q3)*sin(q1)) - cos(q1)*(128*cos(q1)*cos(q2) + 133.4000*cos(q4)*(cos(q1)*cos(q2)*cos(q3) - cos(q1)*sin(q2)*sin(q3)) - 133.4000*sin(q4)*(cos(q1)*cos(q2)*sin(q3) + cos(q1)*cos(q3)*sin(q2)) + 148*cos(q1)*cos(q2)*cos(q3) - 148*cos(q1)*sin(q2)*sin(q3)), sin(q1)*(133.4000*cos(q4)*(sin(q1)*sin(q2)*sin(q3) - cos(q2)*cos(q3)*sin(q1)) + 133.4000*sin(q4)*(cos(q2)*sin(q1)*sin(q3) + cos(q3)*sin(q1)*sin(q2)) + 148*sin(q1)*sin(q2)*sin(q3) - 148*cos(q2)*cos(q3)*sin(q1)) - cos(q1)*(133.4000*cos(q4)*(cos(q1)*cos(q2)*cos(q3) - cos(q1)*sin(q2)*sin(q3)) - 133.4000*sin(q4)*(cos(q1)*cos(q2)*sin(q3) + cos(q1)*cos(q3)*sin(q2)) + 148*cos(q1)*cos(q2)*cos(q3) - 148*cos(q1)*sin(q2)*sin(q3)), sin(q1)*(133.4000*cos(q4)*(sin(q1)*sin(q2)*sin(q3) - cos(q2)*cos(q3)*sin(q1)) + 133.4000*sin(q4)*(cos(q2)*sin(q1)*sin(q3) + cos(q3)*sin(q1)*sin(q2))) - cos(q1)*(133.4000*cos(q4)*(cos(q1)*cos(q2)*cos(q3) - cos(q1)*sin(q2)*sin(q3)) - 133.4000*sin(q4)*(cos(q1)*cos(q2)*sin(q3) + cos(q1)*cos(q3)*sin(q2)))],
                    [                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                          -sin(q1),                                                                                                                                                                                                                                                                                                                                                                                                                              -sin(q1),                                                                                                                                                                                                                                                                                                      -sin(q1)],
                    [                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cos(q1),                                                                                                                                                                                                                                                                                                                                                                                                                               cos(q1),                                                                                                                                                                                                                                                                                                       cos(q1)],
                    [                                                                                                                                                                                                                            1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                             0]
 
        ]
numpy_J = np.array(J)
x = np.matmul(J,vels.T)
print(J)

print("END-EFFF: ",x)


# self.J = [[- 128*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) - 148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) - 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)),           - 128*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) - 148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) - 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)),     -(cos(q1)*cos(q2) + sin(q1)*sin(q2))*(128*cos(q3) + 148*cos(q3)*cos(q4 + pi/2) - 148*sin(q3)*sin(q4 + pi/2)),          -(cos(q1)*cos(q2) + sin(q1)*sin(q2))*(148*cos(q3)*cos(q4 + pi/2) - 148*sin(q3)*sin(q4 + pi/2))],
        #     [  128*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)),             128*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)),      (cos(q1)*sin(q2) - cos(q2)*sin(q1))*(128*cos(q3) + 148*cos(q3)*cos(q4 + pi/2) - 148*sin(q3)*sin(q4 + pi/2)),           (cos(q1)*sin(q2) - cos(q2)*sin(q1))*(148*cos(q3)*cos(q4 + pi/2) - 148*sin(q3)*sin(q4 + pi/2))],
        #     [   0,                                                                                                                                                                                              0,         (cos(q1)*cos(q2) + sin(q1)*sin(q2))*(128*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2))) - (cos(q1)*sin(q2) - cos(q2)*sin(q1))*(128*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) + 148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) + 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1))),            (cos(q1)*cos(q2) + sin(q1)*sin(q2))*(148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2))) - (cos(q1)*sin(q2) - cos(q2)*sin(q1))*(148*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) + 148*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))],
        #     [   0,                                                                                                                                                                                              0,         cos(q2)*sin(q1) - cos(q1)*sin(q2),            cos(q2)*sin(q1) - cos(q1)*sin(q2)],
        #     [   0,                                                                                                                                                                                              0,       - cos(q1)*cos(q2) - sin(q1)*sin(q2),          - cos(q1)*cos(q2) - sin(q1)*sin(q2)],
        #     [   1,                                                                                                                                                                                              1,              0,             0] ]

        # self.J = [
# 
                    # [- 128*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) - (1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5 - (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5, - 128*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) - (1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5 - (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5,                                                                                                                                                                                                                                                                                                                                                -(cos(q1)*cos(q2) + sin(q1)*sin(q2))*(128*cos(q3) + (1407*cos(q3)*cos(q4 + pi/2))/5 - (1407*sin(q3)*sin(q4 + pi/2))/5),                                                                                                                                                                                                                                                          -(cos(q1)*cos(q2) + sin(q1)*sin(q2))*((1407*cos(q3)*cos(q4 + pi/2))/5 - (1407*sin(q3)*sin(q4 + pi/2))/5)],
                    # [  128*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + (1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5 + (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5,   128*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + (1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5 + (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5,                                                                                                                                                                                                                                                                                                                                                 (cos(q1)*sin(q2) - cos(q2)*sin(q1))*(128*cos(q3) + (1407*cos(q3)*cos(q4 + pi/2))/5 - (1407*sin(q3)*sin(q4 + pi/2))/5),                                                                                                                                                                                                                                                           (cos(q1)*sin(q2) - cos(q2)*sin(q1))*((1407*cos(q3)*cos(q4 + pi/2))/5 - (1407*sin(q3)*sin(q4 + pi/2))/5)],
                    # [                                                                                                                                                                                            0,                                                                                                                                                                                             0, (cos(q1)*cos(q2) + sin(q1)*sin(q2))*(128*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)) + (1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5 + (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5) - (cos(q1)*sin(q2) - cos(q2)*sin(q1))*(128*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)) + (1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5 + (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5), (cos(q1)*cos(q2) + sin(q1)*sin(q2))*((1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5 + (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*cos(q2) - sin(q1)*sin(q2)))/5) - (cos(q1)*sin(q2) - cos(q2)*sin(q1))*((1407*cos(q3)*sin(q4 + pi/2)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5 + (1407*cos(q4 + pi/2)*sin(q3)*(cos(q1)*sin(q2) + cos(q2)*sin(q1)))/5)],
                    # [                                                                                                                                                                                            0,                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                                                                                                                                                                     cos(q2)*sin(q1) - cos(q1)*sin(q2),                                                                                                                                                                                                                                                                                                                                 cos(q2)*sin(q1) - cos(q1)*sin(q2)],
                    # [                                                                                                                                                                                            0,                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                                                                                                                                                                   - cos(q1)*cos(q2) - sin(q1)*sin(q2),                                                                                                                                                                                                                                                                                                                               - cos(q1)*cos(q2) - sin(q1)*sin(q2)],
                    # [                                                                                                                                                                                            1,                                                                                                                                                                                             1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                 0]
#  
# 
# 
        # ]